// Generated by CoffeeScript 1.3.3
(function() {
  var ShittyRouter, exports;

  exports = module.exports = ShittyRouter = (function() {

    function ShittyRouter() {
      this.routes = [];
    }

    ShittyRouter.prototype.addRouteRegex = function(match, params, callback) {
      if (!(callback != null)) {
        callback = params;
        params = null;
      }
      return this.routes.push({
        match: match,
        params: params,
        callback: callback
      });
    };

    ShittyRouter.prototype.match = function(path, extraparams) {
      var i, param, params, results, route, _i, _j, _len, _len1, _ref, _ref1;
      _ref = this.routes;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        route = _ref[_i];
        results = route.match.exec(path);
        if (results != null) {
          params = {};
          _ref1 = route.params;
          for (i = _j = 0, _len1 = _ref1.length; _j < _len1; i = ++_j) {
            param = _ref1[i];
            params[param] = results[i + 1];
          }
          route.callback(params, extraparams);
          return true;
        }
      }
      return false;
    };

    return ShittyRouter;

  })();

}).call(this);
